# Generated by Django 6.0.4 on 2026-05-05 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tugas',
            name='deadline',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
