# Generated by Django 5.2.5 on 2026-05-06 15:20

import elearning.upload_security
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tugas',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=elearning.upload_security.secure_tugas_upload_path, validators=[elearning.upload_security.validate_secure_uploaded_file]),
        ),
    ]
